### ISSUE TITLE
[bug] Dbeaver show create table 

### ISSUE THREAD

**Issue by hantmac** [databendlabs/databend-jdbc#172]
In Dbeaver, the DDL show create table is shown as:

<img width="746" alt="image" src="https://github.com/datafuselabs/databend-jdbc/assets/7600925/6e571eec-cd3a-43e6-9e1d-7ff612b77278">

But the table in databend should show create table as:

![image](https://github.com/datafuselabs/databend-jdbc/assets/7600925/91d37d10-0eea-416e-b2c7-9e2db44f6c87)

```
CREATE TABLE `source_table` (
  `id` INT NULL,
  `name` VARCHAR NULL,
  `age` INT NULL,
  `city` VARCHAR NULL
) ENGINE=FUSE
```

Dbeaver should shown the same with bendsql.

**Comment by hanxuanliang** [comment]
1. create a table in dbserver
2. In the databend bendsql, the create table sql is inconsistent. The field type is missing

Is that case?

**Comment by hantmac** [comment]
> 1. create a table in dbserver
> 2. In the databend bendsql, the create table sql is inconsistent. The field type is missing
> 
> Is that case? @hantmac

The field nullable is missing. In dbeaver , there is no `NULL` .

**Comment by hanxuanliang** [comment]
https://github.com/dbeaver/dbeaver/issues/23101

I submitted my question to DBeaver. Let's see if there are any settings that we haven't noticed.

**Comment by hanxuanliang** [comment]
https://github.com/dbeaver/dbeaver/blob/69eef4faa5735071be386281c2d752eba88dcf82/plugins/org.jkiss.dbeaver.ext.clickhouse/src/org/jkiss/dbeaver/ext/clickhouse/model/ClickhouseMetaModel.java#L121

We need to implement getTableDDL, and dbeaver can display DDL directly using the logic we implemented.

**Comment by rad-pat** [comment]
@hantmac, @hanxuanliang 
I have picked up from where your DBeaver contribution left off and have got it somewhat working. The SHOW CREATE TABLE is now working, it was using the incorrect column from dataset. 
Somehow the driver seems to be picking up tables that do not exist. I will try to look more on Monday.  
We are keen to have the DBeaver contribution to manage Databend system properly. 

To set up development environment for DBeaver did not take long, following instructions here https://dbeaver.com/docs/dbeaver/Develop-in-Eclipse/24.0/

Database version does not work because it is not working from JDBC driver. https://github.com/datafuselabs/databend-jdbc/issues/204

My changes so far are stored here https://github.com/rad-pat/dbeaver/tree/support-databend
Only one commit more than you had previously, just to get things working.

**Comment by hantmac** [comment]
> @hantmac, @hanxuanliang I have picked up from where your DBeaver contribution left off and have got it somewhat working. The SHOW CREATE TABLE is now working, it was using the incorrect column from dataset. Somehow the driver seems to be picking up tables that do not exist. I will try to look more on Monday. We are keen to have the DBeaver contribution to manage Databend system properly.
> 
> To set up development environment for DBeaver did not take long, following instructions here https://dbeaver.com/docs/dbeaver/Develop-in-Eclipse/24.0/
> 
> Database version does not work because it is not working from JDBC driver. #204
> 
> My changes so far are stored here https://github.com/rad-pat/dbeaver/tree/support-databend Only one commit more than you had previously, just to get things working.

Thanks for your works!

**Comment by rad-pat** [comment]
Patch for supporting Databend in DBeaver is now merged, so it is possible that this issue is completed. 
https://github.com/dbeaver/dbeaver/pull/35639

**Comment by hantmac** [comment]
> Patch for supporting Databend in DBeaver is now merged, so it is possible that this issue is completed. [dbeaver/dbeaver#35639](https://github.com/dbeaver/dbeaver/pull/35639)

@rad-pat Awesome！ Thanks for your contribution! ❤
